# Generated by Django 3.1.6 on 2021-09-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticizes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Titre'),
        ),
    ]
