# Generated by Django 3.1.6 on 2021-10-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criticizes', '0005_auto_20210924_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
